spring:
  application:
    name: retail-banking-api-gateway

  cloud:
    gateway:
      routes:
        - id: retail-banking-user-service
          uri: lb://retail-banking-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: retail-baning-fund-transfer-service
          uri: lb://retail-banking-fund-transfer-service
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1
        - id: retail-core-banking-service
          uri: lb://retail-core-banking-service
          predicates:
            - Path=/banking-core/**
          filters:
            - StripPrefix=1

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

